
import { Inter } from "next/font/google"
import "../globals.css";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Auth',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <AuthProvider>
      <body className={`${inter.className} bg-black`}>{children}</body>
      </AuthProvider>
    </html>
  )
}
