
import './globals.css'
import { Inter } from 'next/font/google'
import 'flowbite';
import TopBar from '@/components/shared/TopBar';
import SideBar from '@/components/shared/SideBar';
import BottomBar from '@/components/shared/BottomBar';
import AuthProvider from '@/components/AuthProvider/AuthProvider';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <TopBar/>
        <main className='flex'>
        <SideBar/>
        <section className='flex min-h-screen flex-1 flex-col items-center bg-black px-6 pb-10 pt-28 max-md:pb-32 sm:px-10'>
              <div className='w-full max-w-4xl'>{children}</div>
            </section>
              </main>
        <BottomBar/>
        </AuthProvider>
        </body>
    </html>
  )
}
